baseURL = "https://vmpr0be.github.io"
title = "vmpr0be's blog"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
googleAnalytics = ""
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, vmpr0be"
minify = true

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/post/"
weight = -100

[[menu.main]]
identifier = "contact"
name = "Contact"
title = "Contact"
url = "/contact/"
weight = -80

[params]
description = "vmpr0be's blog"
header_title = "vmpr0be"
header_subtitle = "cybersecurity enthusiast"
home_image = "images/avatar.png"
recent_posts = 0
mainSections = ["posts"]
[params.style]
backgroundColor = "#f8f9fa"
fontColor = "#212529"

[[params.social]]
fa_icon = "fab fa-github fa-1x"
href = "https://github.vmpr0be.com"

[[params.social]]
fa_icon = "fab fa-x fa-1x"
href = "https://x.vmpr0be.com"
